### ISSUE TITLE
RPS 2021

### ISSUE THREAD

**Issue by amastrobera** [architecture-building-systems/revitpythonshell#106]
Dear RPS, 

when are you going to release the 2021 version ? v2020 does not work for the new revit. 
Thank you

**Comment by Thomas84** [comment]
it should work if you copy the files ( C:\Program Files (x86)\RevitPythonShell\2020 ) and the addin file (  %userprofile%\AppData\Roaming\Autodesk\Revit\Addins\2020 ) to 2021 folders and adjust the path in the *.addin file to 2021

**Comment by ArielAmador** [comment]
my friend did what he indicated and I get an error, announcing that a part of the path is missing referring a * .xml file

**Comment by Thomas84** [comment]
> an error, announcing that a part of the path is missing referring a * .xml file

which xml file exactly? can you please show us an screenshot or copy the complete error message

**Comment by ArielAmador** [comment]
Thanks friend for the concern, but I already solved it, what I had to do
was change the name of the folder that the installation creates in "C: \
Users \ ***** \ AppData \ Roaming \ RevitPythonShell \ 2020" and put 2021,
that solves the problem. For more information see the following link,
referring to revit 2017 but which works for revit 2021:
https://github.com/architecture-building-systems/revitpythonshell/issues/63

**Comment by jeremytammik** [comment]
I found it easy to install the Revit 2020 version for Revit 2021. I copied the add-in manifest `RevitPythonShell.addin` from `C:\Users\jta\AppData\Roaming\Autodesk\Revit\Addins\2020` to `C:\Users\jta\AppData\Roaming\Autodesk\Revit\Addins\2021` and made a copy of the entire contents of `C:\Users\jta\AppData\Roaming\RevitPythonShell\2020`, copying that to a new directory `C:\Users\jta\AppData\Roaming\RevitPythonShell\2021`.

**Comment by amastrobera** [comment]
works for me like it does for Jeremy.
