### ISSUE TITLE
Revit 2020 RPS wont load in Ribbon 

### ISSUE THREAD

**Issue by smaren1019** [architecture-building-systems/revitpythonshell#108]
Downloaded the installer. 

Copied the files inside to: 

C:\Users\USer\AppData\Roaming\Autodesk\Revit\Addins\2020 

created an .addin following other posts: 

`<?xml version="1.0" encoding="utf-16" standalone="no"?>
<RevitAddIns>
  <AddIn Type="Application">
    <Name>RevitPythonShell</Name>
    <Assembly>C:\Program Files (x86)\RevitPythonShell2020\2020\RevitPythonShell.dll</Assembly>
    <AddInId>3a7a1d24-51ed-462b-949f-1ddcca12008d</AddInId>
    <FullClassName>RevitPythonShell.RevitPythonShellApplication</FullClassName>
  <VendorId>RIPS</VendorId>
  </AddIn>
</RevitAddIns>`  

I get the error: 
![image](https://user-images.githubusercontent.com/60147431/82160858-64dbf400-9855-11ea-872f-ad765c1db33b.png) 

Any ideas on solution?

**Comment by daren-thomas** [comment]
@smaren1019 were you able to solve this? how?

**Comment by smaren1019** [comment]
Yes. Downloaded the installer on a personal computer to get access to all the files. Copied the addin file and XML file in the right places following the errors.
