### ISSUE TITLE
Need create a branch dev to collaborator

### ISSUE THREAD

**Issue by chuongmep** [architecture-building-systems/revitpythonshell#123]
Dear @daren-thomas 
When we work with CI/CD process, we need to add a branch dev to collaborator because when user push code to this, it will be not run in publish new version.
https://github.com/architecture-building-systems/revitpythonshell/blob/b3e74ae1d7e64ad4ce492f293a738c66502ed1ac/.github/workflows/Workflow.yml#L9

**Comment by daren-thomas** [comment]
I created a branch called `develop`. is that good enough?

**Comment by chuongmep** [comment]
@daren-thomas sorry about issues this, it a mistake when i see update don't have branch develop, at the moment it is enough for process, thanks so much !
