### ISSUE TITLE
Support for Revit 2023?

### ISSUE THREAD

**Issue by emilaz** [architecture-building-systems/revitpythonshell#127]
Hi,
thanks for still maintaining this super useful software :) 
I was wondering when there'll be a release for the Revit 2023 version?

Cheers

**Comment by jmcouffin** [comment]
check here https://github.com/architecture-building-systems/revitpythonshell/releases
the latest is supposed to support 2023
Haven't tried it on my laptop, but worked on my desktop

**Comment by jmcouffin** [comment]
![image](https://user-images.githubusercontent.com/7872003/185605007-e892a6ac-77bd-4549-8b3f-716ebb10c2e6.png)
it works fine.
Please try and close the issue
