### ISSUE TITLE
I am getting issue in placing doors in revit using iron python shell

### ISSUE THREAD

**Issue by S-Rafay-Ali-bukhari** [architecture-building-systems/revitpythonshell#130]
System.InvalidOperationException: Operation is not valid due to the current state of the object.   This is the error I am getting.
[Placing Doors.txt](https://github.com/architecture-building-systems/revitpythonshell/files/9573845/Placing.Doors.txt)

**Comment by jmcouffin** [comment]
collect the wall location curve then locate the point for door insertion

could not use the hardcoded ids you used but it does work this way for example

```
sel = selection

doc = __revit__.ActiveUIDocument.Document
t = Transaction(doc,"Create Walhhhls")
walls = []
lns = []
t.Start()
for s in sel:
	ln = s.GeometryCurve
	
	wall = Wall.Create(doc, ln, ElementId(55663), ElementId(111861), 10, 0, False, False)
	walls.append(wall)
	lc_w = wall.Location.Curve
	lns.append(lc_w)
t.Commit()

t.Start()
door_sym = doc.GetElement(ElementId(241711))


for ln in lns:
	pt = ln.Evaluate(0.5, 0)
	try:
		for wall in walls:
			door = doc.Create.NewFamilyInstance(pt, door_sym ,wall, Structure.StructuralType.NonStructural)
	except:
		pass
t.Commit()
```
Note, no need to import the revit api modules

**Comment by S-Rafay-Ali-bukhari** [comment]
Thanks a lot! Do you give classes for teaching coding? I am learning basics however I want to learn advance coding.

**Comment by jmcouffin** [comment]
> Thanks a lot! Do you give classes for teaching coding? I am learning basics however I want to learn advance coding.

@S-Rafay-Ali-bukhari 

I do sometimes. You can contact [BIMOne inc.](https://www.bimone.com/), the company I work for and ask for a quote if you want.

There is also a lot of free stuff around, I will point you a few:

- https://www.notion.so/Create-Your-First-Command-2509b43e28bd498fba937f5c1be7f485 101 of coding stuff in python within the pyrevit environment in revit
- https://www.notion.so/HOW-TO-Guides-dc20e0e227b74d9bbc775699904152cb more advanced stuff with pyRevit
- https://www.youtube.com/c/ErikFrits beginner, but good base for undertanding
- https://www.youtube.com/c/pyRevit more advanced
- lost of good bases https://www.youtube.com/c/DannyBentley/videos
- and mine, the latest lab I presented: https://github.com/jmcouffin/pyRevit-BILT_NA_2022 in the handout section
- the pyrevit community forum https://discourse.pyrevitlabs.io/
- the pyrevit docs https://pyrevit1.readthedocs.io/en/latest/index.html
- the revit python shell samples https://github.com/daren-thomas/rps-sample-scripts
- the python primer for dynamo https://dynamopythonprimer.gitbook.io/dynamo-python-primer/
- loads of samples well commented here too https://github.com/Amoursol/dynamoPython
- some nice stuff too from Gavin Grump https://www.youtube.com/c/AussieBIMGuru/playlists

if you go through all that you will know more than I do probably 😃

**Comment by S-Rafay-Ali-bukhari** [comment]
The above code is also not working. Can you please help?

**Comment by jmcouffin** [comment]
It works for my specific revit sample project, 
you need to change `ElementId(55663), ElementId(111861)`
the first one being the walltype id the second the levelId
to grab them use revit lookup tool
https://apidocs.co/apps/revit/2019/6c247699-c8e5-91df-67f7-470d10fa7ba3.htm

**Comment by jmcouffin** [comment]
This is not an issue for revit python shell, so please close the issue
