### ISSUE TITLE
I want to create a code through which I can create walls on the boundary of already modelled walls.

### ISSUE THREAD

**Issue by S-Rafay-Ali-bukhari** [architecture-building-systems/revitpythonshell#131]
I have successfully created wall through script however I am not able to create a script that other walls will be created at the surface of already created walls.

**Comment by PavelAltynnikov** [comment]
This question has nothing to do with the issues of the RPS, please don't post stuff like this here and close this issue.

**Comment by daren-thomas** [comment]
@S-Rafay-Ali-bukhari To expand on @PavelAltynnikov 's answer, the RPS just provides python _access_ to the Revit API. There are better places to learn how to actually _use_ the API. We've tried to list some resources in the [Getting Started](https://github.com/architecture-building-systems/revitpythonshell#getting-started) section of the README in this repo.

If you find some better resources or forums that might help others with questions we'll gladly add links to that section, please tell us!

As I'm not involved with the Revit community anymore, I'm not currently aware of the _goto_ place to ask such questions, I'm sorry. But there probably _is_ such a place and it would benefit other users with such questions, if they tend to be asked in the same place - it will make those questions easier to find for other people too. Splitting up the community by answering such questions in the RPS repo would only weaken the community.

Good luck with creating your RPS script! I do hope you eventually find the answer you're looking for!!!
