### ISSUE TITLE
UNABLE TO INSTALL NEW VERSION ISSUE WITH REVIT 2021

### ISSUE THREAD

**Issue by ngbwater** [architecture-building-systems/revitpythonshell#150]
![image](https://github.com/architecture-building-systems/revitpythonshell/assets/155345140/58f11953-0638-49f6-acb1-a53abab9dabb)

**Comment by iorhanV** [comment]
This just happened to me and I fixed it running the .msi installer as admin. If you cannot access "Run as administrator" with right-click you can try running it via CMD.

https://www.uc.solutions/Microsoft_Teams/MS_Teams_Admin/MS_Teams_Admin_Portal/MS_Teams_Admin_-_Run_.msi_Files_As_Administrator

**Comment by ngbwater** [comment]
> This just happened to me and I fixed it running the .msi installer as admin. If you cannot access "Run as administrator" with right-click you can try running it via CMD.
> 
> https://www.uc.solutions/Microsoft_Teams/MS_Teams_Admin/MS_Teams_Admin_Portal/MS_Teams_Admin_-_Run_.msi_Files_As_Administrator

**Comment by ngbwater** [comment]
Thank you!! this worked perfectly
