### ISSUE TITLE
can't get revitpythonshell button to show up in add-ins

### ISSUE THREAD

**Issue by PA-shell** [architecture-building-systems/revitpythonshell#162]
I am using the guide below to install Revit python shell for Revit 2022 and I received the error message in the snippet when starting.
I noticed that the guide shows "commandloaderassembly.dll" in the directory, which is not in the master code zip; Is that my problem?

*i see someone else asked the same question months ago, but I don't think the issue was resolved*
https://bimregime.wordpress.com/2020/07/26/how-to-install-and-run-revit-python-shell/

![todayScreenshot 2024-12-04 093232](https://github.com/user-attachments/assets/acb96db1-da4d-4eeb-abce-15ba1e49e9ab)

**Comment by Ianhuuuuang** [comment]
您好，邮件已收到，尽快给您回复。

**Comment by PA-shell** [comment]
I solved my issue by using an online GUID generator and placed it in the XML file (in the appropriate string).
