### ISSUE TITLE
Fatal Error when running hitting the run button

### ISSUE THREAD

**Issue by engsabbagh** [architecture-building-systems/revitpythonshell#30]
I am using the Revit structure 2015 update release 9)
i am facing fatal error every time hit the run button even for a sample code , Any Help
![test2](https://cloud.githubusercontent.com/assets/12892747/9330086/86003e0e-45bf-11e5-9626-784be260fdf0.png)
![test1](https://cloud.githubusercontent.com/assets/12892747/9330085/85fee9dc-45bf-11e5-8828-15217cbfd1f3.png)

**Comment by daren-thomas** [comment]
does the error happen when you press "."?

**Comment by engsabbagh** [comment]
Hi Daren,

Thank you for your quick reply.
 No , I am getting this fatal error every time I click on the Run Button even with empty code .

Thx. for ur help.

**Comment by daren-thomas** [comment]
that is really strange. which version are you running? 2015.05.21?

can you run an external script?

as it is, this is very hard to debug. Try installing an external script
(with the configure dialog, just download one from the rps-samples
repository on github) and see if that produces the same results.

**Comment by engsabbagh** [comment]
The version available on https://github.com/architecture-building-systems/revitpythonshell is 2015.0

**Comment by daren-thomas** [comment]
did you build it yourself or download the release 2015.05.21 from the releases section?

**Comment by apothetron** [comment]
I get the same error. I am running Revit 2015 Update 9 with RevitPythonShell 2015.04.29 . I tried a fresh install with no updates and got the same error on 3 different computers. I am simply just trying to run a print 'Hello World' to get started.

**Comment by daren-thomas** [comment]
thank you. i'll look into it next week.

**Comment by hienngocloveyou** [comment]
Yes, now i have a same issue ??? same error with @engsabbagh

**Comment by daren-thomas** [comment]
It could be the IronPython version - RPS bundles its own IronPython (2.7.3). In fact, just installing IronPython 2.7.5 makes Revit crash when RPS is configured with a startup script. I'm investigating.

**Comment by colinrichardson** [comment]
I had the same error and saw somewhere else that reverting to ironpython 2.7.4 worked for me.

**Comment by daren-thomas** [comment]
Yes, currently RPS will not work if IronPython 2.7.5 is installed. I do not know how to fix this. I think it might be out of my control and a Revit issue but cannot really prove this. Separating the RPS shell into its own application works fine with the newer version of IronPython, only when integrated with Revit does this issue show up. I won't be fixing this due to time constraints. Sorry.
