### ISSUE TITLE
Revitpythonshell does not appear in Add-ins tab

### ISSUE THREAD

**Issue by boesiii** [architecture-building-systems/revitpythonshell#34]
The Revitpythonshell does not show up in the Add-ins tab under my typical username but if I run Revit using the administrator account the tool appears in the Add-ins tab.  What can I do to get the tool to appear for my tyical username which does not have admin rights?

**Comment by daren-thomas** [comment]
This question was also raised in the RevitPythonShell forum, here is an answer I thought looked promising:

>Hello,
>
>You probably installed RPS not for all users. By default RPS addin file is installed here : >%AppData%\Autodesk\Revit\Addins\2016 (Usually C:\Users\<user >name>\AppData\Roaming\Autodesk\Revit\Addins\2016)
>This path refer to one user path, you should check this path under your admin account.  >RevitPythonShell2016.addin should be there.
>
Doing one of the following should work :
>- copy RevitPythonShell2016.addin in the non admin %AppData%\Autodesk\Revit\Addins\2016 it will >install it only for the specific user you copied the file in.
>- copy RevitPythonShell2016.addin in %ProgramData%\Autodesk\Revit\Addins\2016 It should install it >for all users.
>
>Cheers

**Comment by boesiii** [comment]
That worked please close the issue

**Comment by daren-thomas** [comment]
Closing issue as resolved.
