### ISSUE TITLE
Can't find file error on first start

### ISSUE THREAD

**Issue by TStrathaus** [architecture-building-systems/revitpythonshell#40]
Hi
I installed IronPython 2.7.6.3 and Revit Python Shell for 2016.
On the first start of Revit I get the error message

Error setting up RevitPythonShell
System.IO.FileNotFoundEception: COuld not load fole or assembly 'IronPython, Version 2.7.0.40, Culture=neutral
PublicKeyToken or one of its dependencies

Wondering both that it doesn't work, and that the IronPython versions seems to differ, 2,7.0.40 versus 2.7.6.3

Would be thankful for any hint
Thorsten

**Comment by eirannejad** [comment]
Uninstall the independent IronPython and RevitPythonShell will load.

**Comment by TStrathaus** [comment]
That did the trick,
thanks a lot!

T

**Comment by eirannejad** [comment]
Your welcome. You can't really use the independent IronPython with Revit anyway since Revit is thread safe and only the main thread can make changes to its database. RevitPythonShell is the best terminal for learning how to use IronPython with Revit.
