### ISSUE TITLE
Can't install Revitpythonshell on Revit 2017

### ISSUE THREAD

**Issue by ThongPhan89** [architecture-building-systems/revitpythonshell#54]
Dear all,
 
I've just downloaded and installed the latest revitpythonshell for revit 2017 but it doesn't show in Add-in. Please give me an advice to solve it.

Thank all!

**Comment by daren-thomas** [comment]
- Is there a folder `%APPDATA%\Autodesk\Revit\Addins` on your computer? 
- Does it have a subfolder  `2017`? 
- Does that have the file `RevitPythonShell2017.addin` in it?
- How exactly did you install the software? 
  - Which setup file did you use?
  - What options did you choose?

**Comment by ThongPhan89** [comment]
I've just check and copy the file to the folder. 
I downloaded the file from your post here. And when I start the revit, it appears the error dialog.
![image](https://cloud.githubusercontent.com/assets/28525991/25795173/61aa5e84-33fe-11e7-834a-2c8e8d43eedf.png)
Can you review it? 
Thank Daren.

**Comment by ThongPhan89** [comment]
Dear Daren,

I fixed that. 

Thank for your support!

**Comment by daren-thomas** [comment]
what was the solution?

**Comment by ThongPhan89** [comment]
The file only appeared in the folder of Admin, not in user, so I copied the file to folder user.
After opening Revit, it showed the error dialog "missing file blah blah blah"
So I did copy all files from folder Pythonshell in this topic into the folder they want and everything done!

**Comment by daren-thomas** [comment]
thank you. you have just made the internet a better place! (the next user with this problem can find the solution...)
