### ISSUE TITLE
ETA for Revit 2018 Installer?

### ISSUE THREAD

**Issue by eirannejad** [architecture-building-systems/revitpythonshell#56]

**Comment by abatod** [comment]
Waiting... :-)

**Comment by daren-thomas** [comment]
Oh, Revit 2018 is out? I guess I need to get my license renewed... I don't have a plan right now, but I might have some time end of the week.

**Comment by daren-thomas** [comment]
BTW: anyone want to help beta-testing the installer when it comes out?

**Comment by htlcnn** [comment]
I'm using Revit 2018 and am willing to test

**Comment by daren-thomas** [comment]
Here is a preliminary version: https://www.dropbox.com/s/jcdq5mwzsig0w45/Setup_RevitPythonShell_2018.iss?dl=0

I'd be interested to know of any problems...

**Comment by htlcnn** [comment]
Excuse me, how do I use this .iss file to install?

**Comment by eirannejad** [comment]
You gotta combile RPS on your machine, install InnoSetup tool that reads the ISS files. Then create the setup package from the ISS file

**Comment by htlcnn** [comment]
.iss file contains paths to file that I don't have on my computer, neither can I find them on this repo. How can I get these files?

**Comment by eirannejad** [comment]
The RPS code needs to be compiled for InnoSetup to be able to find the files

**Comment by htlcnn** [comment]
Then I'm supposed to have Visual Studio on my computer and know how to build a C# project to dll files?

**Comment by eirannejad** [comment]
Yeap. Or just wait till Daren publishes the exe installer which should be soon.

**Comment by daren-thomas** [comment]
@htlcnn I'm very sorry. In my rush to provide you with a setup file to test while I was on vacation, I accidentally sent the wrong file. Try this one instead: https://www.dropbox.com/s/h55ljwvy5weohrj/2017.07.24_Setup_RevitPythonShell_2018.exe?dl=0

**Comment by abatod** [comment]
![image](https://user-images.githubusercontent.com/27179128/28519593-2ae94ef6-70a7-11e7-96e8-36dbaef9b2e3.png)
When open Revit, this window appear. After open it, looks working well.

**Comment by daren-thomas** [comment]
hm... @abatod: do you have a manual installation that might be in the way?

**Comment by abatod** [comment]
Just downloaded this file and installed. https://www.dropbox.com/s/h55ljwvy5weohrj/2017.07.24_Setup_RevitPythonShell_2018.exe?dl=0
After close that window, pythonshell woks fine. 
Actually I installed in two machines. One has already installed phytonshell 2017 and another one is just new installed. Both of they shows me that error when open Revit.
Anyhow thank you for developing PythonShell.

**Comment by daren-thomas** [comment]
Ah yes... I get that error too. Wait. Let me investigate.

**Comment by htlcnn** [comment]
I tried to compile rps myself and got that error too. Rps didn't work either. Compiling the dlls didn't go on very well, revitpythonshell project seems to reference 2014 revitapi and revitapiui. I tried to change to 2018 dlls and set target framework to 4.6 but didn't succeed.

**Comment by daren-thomas** [comment]
I just pushed a fix for the issue on loading and updated the setup file linked above. @abatod: maybe you could check the error again?

**Comment by daren-thomas** [comment]
@htlcnn before compiling, make sure you select the correct solution configuration. it should be "Debug 2018". Then, the solution should reference the proper APIs...

**Comment by CyrilWaechter** [comment]
On my computer it solved the error message (got the same as @abatod). I tried some stuff in console, everything seems to work fine.
Thanks a lot @daren-thomas we are now ready to move on 2018.1 ^^

**Comment by htlcnn** [comment]
Recent update fixed the error. RPS run well on Revit 2018.1 (Windows 7 x64). Thank you very much @daren-thomas !

**Comment by daren-thomas** [comment]
OK. I've created a release and updated the readme page to link to the installer. Thank you for your help everyone!
