### ISSUE TITLE
Text in Pad disappears after opening a python script

### ISSUE THREAD

**Issue by htlcnn** [architecture-building-systems/revitpythonshell#62]
This happens to both Interactive and Non-modal Shell.
I opened the Shell, pressed Open Python script immediately and chose a file. The file was loaded successfully but as soon as I click in the pad to edit text, they disappeared.
It only happens when the cursor is not active in the pad before opening the file.
To avoid this bug, I have to click in the pad to make the cursor active first, then open saved script.

**Comment by daren-thomas** [comment]
@htlcnn I have been able to reproduce this. Let's see if we can figure out a work-around.

**Comment by daren-thomas** [comment]
I think I fixed this. Try this installer and see if it works: https://github.com/architecture-building-systems/revitpythonshell/blob/c749a8683a0e184240e92228eaedd5900f61eb23/Output/2018.01.04_Setup_RevitPythonShell_2018.exe

**Comment by eirannejad** [comment]
This is the result of a change I made a long time ago to clear the default window contents when user clicks inside the window. Sorry :/

**Comment by daren-thomas** [comment]
@eirannejad did you try the new installer? does it work for you? I'm pretty sure I fixed it, so one additional vote would be cool and then I'll merge...

**Comment by eirannejad** [comment]
Yeap this is fixed. Thanks @daren-thomas
