### ISSUE TITLE
Fix installation guide for Ubuntu

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/revitpythonshell#71]
The prerequisites are not necessary as the guide doesn't use them. While we're at it: Go over the guide and fix up any other issues.

**Comment by htlcnn** [comment]
@daren-thomas how could you install Revit on Ubuntu?

**Comment by daren-thomas** [comment]
@htlcnn ups. This was meant for another project. I don't have Revit installed on Ubuntu. Huh... i wonder if Wine could do that? But really, I don't see this as a valuable way to spend my energy ;-)
