### ISSUE TITLE
feature request: RPS available without opened model

### ISSUE THREAD

**Issue by hdm-dt-fb** [architecture-building-systems/revitpythonshell#78]
low proirity/convenience: 
I could see quite a few use cases where it would be great to have the ribbon buttons of RevitPythonShell accessible even if there is no current model open. Scripts that check a bunch of families/models in a directory, registering to application event handlers before opening a model and others..

My current workaround: I open a blank model, open the modal shell and close the blank model - but that  feels a little silly.. (-;

**Comment by eirannejad** [comment]
Already merged. Waiting for a new installer

https://github.com/architecture-building-systems/revitpythonshell/pull/73

**Comment by daren-thomas** [comment]
wow! this is so cool! i've had this in the back of my mind for so long. and it was so easy to do...

**Comment by hdm-dt-fb** [comment]
Oh it is still open? It works great, so I guess I close it. (hope that is ok?)
