### ISSUE TITLE
Revit Python Shell - Doesn't showup on revit ribbon 

### ISSUE THREAD

**Issue by rahulchowdhary** [architecture-building-systems/revitpythonshell#79]
Hello,
i have installed RPS for revit 2018 but it Doesn't shows up on my revit ribbon.
Any ideas??
![unbenannt](https://user-images.githubusercontent.com/39521345/40360180-ba07176c-5db4-11e8-91ca-b5fc0d84d695.PNG)

**Comment by eirannejad** [comment]
Look under Add-ins tab. There should be a Revit Python Shell panel.

**Comment by PMoureu** [comment]
Hi
We need more details to help you out (windows version, what you did exactly...)

Have you multiple accounts on your Windows ? Like an administrator and other simple users ?
In this case, check this [comment](https://github.com/architecture-building-systems/revitpythonshell/issues/63#issuecomment-373050838) (just replace 2017 by 2018 in the different paths)

**Comment by eirannejad** [comment]
Hmmm. Let me look into this. It might be a path issue since there is no ‘program files’ and it is ‘programme’

**Comment by rahulchowdhary** [comment]
Hello,
Well it somehow workedout, i copied all the files related to RPS from my %temp% and pasted it into same Directory of my office System in which i couldn't install it properly.

Cheers

**Comment by gunstonej** [comment]
Hi there, 

I'm trying to make the pythonrevitshell work also but nothing relating to pythonrevitshell is appearing in the add-ins tab (as shown here: https://www.youtube.com/watch?v=gC_Vpb527B8)

My Setup:
    Windows7
    Revit2018 installed
    pyRevit installed 

After running the installer (as administrator) a RevitPythonShell2018 folder appeared here:
C:\Program Files (x86)\RevitPythonShell2018 
![image](https://user-images.githubusercontent.com/21370980/58976334-1a39a700-87bf-11e9-84c9-2c86e62c4ceb.png)


but nothing got added to the Addins folder:
C:\ProgramData\Autodesk\Revit\Addins\2018
![image](https://user-images.githubusercontent.com/21370980/58976152-adbea800-87be-11e9-8008-9bb2669b6926.png)


i also checked the admin installer path:
C:\Users\jg.installer\AppData\Roaming\Autodesk\Revit\Addins
as suggested by @daren-thomas here https://github.com/architecture-building-systems/revitpythonshell/issues/63 but there was also nothing relating to pythonrevitshell in there either. 

any help / guidance greatly appreciated! 

cheers

**Comment by CyrilWaechter** [comment]
@gunstonej  So strange to see my 5 years old video again XD.

It looks like for some reason the addin file was not created during the installation. Follow these steps for a quick fix :
1. Create a file called `RevitPythonShell2018.addin`
2. Add following code in it and save it : 
```xml
<?xml version="1.0" encoding="utf-16" standalone="no"?>
<RevitAddIns>
  <AddIn Type="Application">
    <Name>RevitPythonShell</Name>
    <Assembly>C:\Program Files (x86)\RevitPythonShell2018\RevitPythonShell.dll</Assembly>
    <AddInId>3a7a1d24-51ed-462b-949f-1ddcca12008d</AddInId>
    <FullClassName>RevitPythonShell.RevitPythonShellApplication</FullClassName>
  <VendorId>RIPS</VendorId>
  </AddIn>
</RevitAddIns>
```
3. Copy the addin file in your `%APPDATA%\Roaming\Autodesk\Revit\Addins\2018` (the one on you image). Revit should ask you to load RPS.

**Comment by gunstonej** [comment]
Hi @CyrilWaechter , its clearly a timeless classic ;)!
Thanks very much for the speedy response. 

I added the RevitPythonShell2018.addin file:
![image](https://user-images.githubusercontent.com/21370980/59018427-c6ba6e00-883d-11e9-8a09-3cadb19ad4da.png)

Upon opening Revit i was asked if i wanted to load RevitPythonShell to which i said "Always Load". 

I then got the following error:
![image](https://user-images.githubusercontent.com/21370980/59018538-02edce80-883e-11e9-9557-1b98d4128cb3.png)

I naively tried just changing the extension of the code you shared above from .addin to .xml and put it in the location that Revit was pointing at and got the following error:
![image](https://user-images.githubusercontent.com/21370980/59019163-67f5f400-883f-11e9-87d3-906370a0606a.png)

.....

**Comment by CyrilWaechter** [comment]
Please try to place the addin file in `%APPDATA%\Roaming\Autodesk\Revit\Addins\2018` rather than in `%ProgramData%\Autodesk\Revit\Addins\2018`.

**Comment by AndreyArduino86** [comment]
Через что можно создать файл RevitPythonShell2018.addin?

**Comment by SergeyBre** [comment]
@CyrilWaechter I'm sure you figured it out already a year ago, but it might be useful for others. I went through the same thing, a colleague of mine helped me to solve it.
1. Go to C:\Users\username\AppData\Roaming and check if the folder RevitPythonShell2018 is there. If not - create one.
2. go to: https://github.com/architecture-building-systems/revitpythonshell/tree/master/RevitPythonShell/DefaultConfig and create files with the same name in the folder that you just created (copy everything which is inside of those files).
3. Run revit - RevitPythonShell should appear under Add-ins tab on the ribbon
![DefaultConfig](https://user-images.githubusercontent.com/67101336/85010815-ef6b8800-b160-11ea-97e4-4ac5c717d53e.png)

**Comment by davidvadkerti** [comment]
Thanks, the new path for 2022 version is with one additional subfolder for the version `%AppData%\RevitPythonShell\2022`
