### ISSUE TITLE
REVIT Python Shell Grayed out

### ISSUE THREAD

**Issue by trieudnguyen** [architecture-building-systems/revitpythonshell#81]
Hello;

I have tried to install the 2017 revitpythonshell.  I have installed it for both all users and for specific users.  The addin appears when starting REVIT 2017 however it is grayed out.  How do I activate it?

Any help would be greatly appreciated
![saved location](https://user-images.githubusercontent.com/40636701/41989176-639b1896-7a0c-11e8-8040-35ef3e7fa69c.png)
![revit_screenshot](https://user-images.githubusercontent.com/40636701/41989181-66a4bb14-7a0c-11e8-8128-d074f347f142.png)

**Comment by eirannejad** [comment]
Do you have any models open?

**Comment by trieudnguyen** [comment]
As soon as I sent that Github thread I realized my mistake and closed the
conversation.  thank you for the response.

Trieu
