### ISSUE TITLE
Automated crop view plans

### ISSUE THREAD

**Issue by rahulchowdhary** [architecture-building-systems/revitpythonshell#83]
Hello,
I am new to pyRevit and RPS Environment and written a Code attached under new zipped folder that runs perfectly with Dynamo but now would lilke to create a plugIn for that using pyRevit Modules.
I am getting an Errors mostly like """" object has no attribute 'Id' or 'GetTypeId' or 'LevelId'. 
This might be because i am missing importing the correct module????

[Neuer Ordner.zip](https://github.com/architecture-building-systems/revitpythonshell/files/2205505/Neuer.Ordner.zip)

**Comment by eirannejad** [comment]
@rahulchowdhary This is a pyRevit question. Please post the issue [here](https://github.com/eirannejad/pyRevit/issues) and provide full error reports. e.g. if the error says `None object has not attribute Id` then we know that the room variable equals None and it's easier to debug.

Closing this here.
