### ISSUE TITLE
revitpythonshell appears disabled in the Addins ribbon in Revit 2018

### ISSUE THREAD

**Issue by epineda** [architecture-building-systems/revitpythonshell#85]
Hi All,

I'm newbie in Revit and RevitPythonShell. I have made a fresh install of Revit 2018 (18.0.0.420 20170223_1515(x64) ) in a Windows 10, then I installed IronPython 2.7.8 and finally executed 2017.07.24_Setup_RevitPythonShell_2018.exe file, but when I open Revit, the RevitPythonShell button always appears disabled. Is there something I'm doing wrong?

Thank you in advance.

**Comment by PMoureu** [comment]
Hi
RevitPythonShell is enabled only when you open a project, so it appears disabled on Revit homepage.

**Comment by eirannejad** [comment]
@epineda Did this get resolved?

**Comment by eirannejad** [comment]
No response in past 3 months. Closing.
