### ISSUE TITLE
Python Shell stop working

### ISSUE THREAD

**Issue by harrucci** [architecture-building-systems/revitpythonshell#87]
Hello everyone, 

I am using Revit 2017 with the corresponding pythonshell edition. Up to now, everything worked fine. But suddenly it doesn't recognize the very basic functions:

Exception : IronPython.Runtime.UnboundNameException: name 'BuiltInCategory' is not defined

I tried the code on another computer with the same Revit and Python editions and every works fine. So, the problem is not with the code itself. What it could be?

For your information the computer is inside a company network and Revit takes its licence vie a Revit Server.

**Comment by daren-thomas** [comment]
Could you please provide a bit more information? What are the exact steps you take to get to the exception you mentioned above? Is that the only information you recieve?

What do you mean with "very basic functions"? Is that a button you're trying to press? Or do you mean Revit API?

**Comment by oguztuncay** [comment]
i have the same problem. it doesn't seem to recognize the 'BuiltInCategory' from Revit's database.

**Comment by daren-thomas** [comment]
@oguztuncay could you maybe provide a set of steps to reproduce the error?

**Comment by eirannejad** [comment]
@oguztuncay This was probably a bug in the init script right?

**Comment by oguztuncay** [comment]
i don't think so. it was a typo that i made when I was trying to import BuiltInCategory. But now I can't execute 'LookupParamater' for a wall object. It says it's not one of the attributes.

**Comment by eirannejad** [comment]
Share your scripts please.

**Comment by CyrilWaechter** [comment]
There is a typo in 'LookupParamater' => LookupParam**e**ter

**Comment by oguztuncay** [comment]
no there is a typo in my comment not in the script
give me a sec

**Comment by oguztuncay** [comment]
![capture](https://user-images.githubusercontent.com/45979527/50314963-2a7bf500-04b1-11e9-9cdf-68517e310a1f.PNG)

**Comment by CyrilWaechter** [comment]
selection return a list of element. Use selection[0] to call LookupParameter on first element.

**Comment by oguztuncay** [comment]
yes! thanks a lot!
