### ISSUE TITLE
When running a deployed addin: "System.ArgumentNullException: Value cannot be null"

### ISSUE THREAD

**Issue by earp123** [architecture-building-systems/revitpythonshell#88]
Having this error on every script I've tried to deploy, including simple one-line script to test with. 

![image](https://user-images.githubusercontent.com/33456310/47439178-88ba7f00-d771-11e8-8e4c-6952493897d8.png)

Revit 2018.3.1.2
Windows 7

The addin seems to be assembled and installed correctly (with an exe made with Inno Setup), I can see the push button in the Add Ins Ribbon panel, the error shows up when I click on it. 

I'm using the deployment process as instructed by this [post](http://darenatwork.blogspot.com/2013/05/deploying-rps-scripts-with.html?_sm_au_=iVV61ntQf0Nkp7sM): 

Please help!

**Comment by earp123** [comment]
Caused by a bug in the Addin Manifest file selected with 'DeployRPSAddin' function. Essentially the manifest was pointing to nothing, so the dll assembled an empty script.

**Comment by ghkchan** [comment]
Hi Earp123, 
I have a similiar problem, how did you resolve this?

**Comment by Arkangel17** [comment]
earp123 how is this considered closed without a resolution? Or at least something saying it is a bug that has not be fixed yet and provide a work-around if one exists, ha.
