### ISSUE TITLE
Revit 2020

### ISSUE THREAD

**Issue by michaelmontagne** [architecture-building-systems/revitpythonshell#95]
Are there plans for a 2020 build?

**Comment by eibre** [comment]
Yes please! 😄

**Comment by zebex** [comment]
please!

**Comment by telegong** [comment]
Mmm... I don't know if it's the right way. but it works well(?) ^^;;;
I just have copied a file " %userprofile%\AppData\Roaming\Autodesk\Revit\Addins\2019\RevitPythonShell2019.addin" to "\2020\RevitPythonShell2019.addin", 
and then copied a directory
 "%userprofile%\AppData\Roaming\RevitPythonShell2019" to "\RevitPythonShell2020".

**Comment by daren-thomas** [comment]
@alvpickmans produced a setup for Revit 2020: Please try it out - link is in the README.md
